// ============================================
// CORE TYPES
// ============================================

export interface Course {
  id: string;
  name: string;
  instructor?: string;
  location?: string;
  credits: number;
  color: string;
  note?: string;
  schedules: CourseSchedule[];
  createdAt: Date;
  updatedAt: Date;
}

export interface CourseSchedule {
  id: string;
  courseId: string;
  dayOfWeek: number; // 0-6 (Sunday to Saturday)
  startTime: string; // HH:mm format
  endTime: string; // HH:mm format
  weekStart?: number;
  weekEnd?: number;
}

export interface Assignment {
  id: string;
  courseId: string;
  course?: Course;
  title: string;
  description?: string;
  dueDate: Date;
  status: AssignmentStatus;
  priority: Priority;
  remindAt?: number;
  autoPriority?: boolean;
  gpaImpact?: number;
  createdAt: Date;
  updatedAt: Date;
}

export type AssignmentStatus = 'todo' | 'in_progress' | 'completed' | 'overdue';
export type Priority = 'critical' | 'high' | 'medium' | 'low';

export interface Exam {
  id: string;
  courseId: string;
  course?: Course;
  title: string;
  description?: string;
  examDate: Date;
  duration?: number;
  location?: string;
  seatNumber?: string;
  remindAt?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Grade {
  id: string;
  courseId: string;
  course?: Course;
  semester: string;
  score: number;
  gradePoint?: number;
  credits: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Quote {
  id: string;
  content: string;
  author?: string;
  source?: string;
  isBookmarked: boolean;
  createdAt: Date;
}

export interface Settings {
  id: string;
  totalRequiredCredits: number;
  targetGPA: number;
  currentSemester: string;
  reminderEnabled: boolean;
  theme: 'light' | 'dark' | 'system';
}

// ============================================
// NEW TYPES - EXECUTION ENGINE
// ============================================

export interface StudySession {
  id: string;
  courseId: string;
  course?: Course;
  duration: number;
  completed: boolean;
  date: Date;
  startTime?: string;
  endTime?: string;
  notes?: string;
  xpEarned: number;
  linkedTaskId?: string;
  linkedTaskType?: 'assignment' | 'exam';
  createdAt: Date;
}

export interface AIInsight {
  id: string;
  type: InsightType;
  severity: 'info' | 'warning' | 'critical';
  message: string;
  courseId?: string;
  courseName?: string;
  relatedTaskId?: string;
  actionSuggested?: string;
  dismissed: boolean;
  createdAt: Date;
}

export type InsightType = 
  | 'weak_subject' 
  | 'gpa_risk' 
  | 'deadline_pressure'
  | 'missing_assignment'
  | 'study_suggestion'
  | 'achievement'
  | 'warning';

export interface DailyMission {
  id: string;
  taskId: string;
  taskType: 'assignment' | 'exam' | 'study';
  task?: Assignment | Exam;
  priority: Priority;
  reason: string;
  completed: boolean;
  autoGenerated: boolean;
  date: Date;
  createdAt: Date;
}

export interface StudyPlan {
  id: string;
  date: Date;
  sessions: PlannedSession[];
  totalHours: number;
  generatedAt: Date;
}

export interface PlannedSession {
  id: string;
  courseId: string;
  duration: number;
  reason: string;
  priority: Priority;
  completed: boolean;
}

// ============================================
// PERFORMANCE TRACKING
// ============================================

export interface PerformanceStats {
  totalStudyHours: number;
  sessionsCompleted: number;
  currentStreak: number;
  longestStreak: number;
  totalXP: number;
  level: number;
  weeklyGoal: number;
  weeklyProgress: number;
}

export interface GPARiskIndicator {
  status: 'stable' | 'at_risk' | 'critical';
  currentGPA: number;
  targetGPA: number;
  gap: number;
  trend: 'improving' | 'declining' | 'stable';
  atRiskCourses: string[];
}

// ============================================
// COMMAND INPUT
// ============================================

export interface CommandResult {
  success: boolean;
  action: string;
  message: string;
  data?: unknown;
}

export type CommandType = 
  | 'study'
  | 'add_assignment'
  | 'add_exam'
  | 'start_session'
  | 'complete_task'
  | 'show_stats'
  | 'help';

// ============================================
// UTILITY TYPES
// ============================================

export interface WeeklySchedule {
  [key: number]: CourseScheduleWithCourse[];
}

export interface CourseScheduleWithCourse extends CourseSchedule {
  course: Course;
}

export interface ScreenshotRecognitionResult {
  type: 'schedule' | 'grade' | 'credits';
  data: CourseRecognitionData | GradeRecognitionData | CreditRecognitionData;
  confidence: number;
  rawText?: string;
  insights?: AIInsight[];
  suggestedActions?: SuggestedAction[];
}

export interface CourseRecognitionData {
  courses: {
    name: string;
    time?: string;
    location?: string;
    instructor?: string;
    weekRange?: string;
  }[];
}

export interface GradeRecognitionData {
  grades: {
    courseName: string;
    credits: number;
    score: number | string;
    gradePoint?: number;
  }[];
}

export interface CreditRecognitionData {
  totalCredits: number;
  completedCredits: number;
  categories: {
    name: string;
    required: number;
    completed: number;
  }[];
}

export interface SuggestedAction {
  type: 'create_task' | 'schedule_study' | 'set_priority';
  description: string;
  priority: Priority;
  relatedCourse?: string;
}

export interface DashboardStats {
  todayCourses: CourseScheduleWithCourse[];
  upcomingAssignments: Assignment[];
  upcomingExams: Exam[];
  currentGPA: number;
  completedCredits: number;
  totalCredits: number;
  dailyMission: DailyMission | null;
  gpaRisk: GPARiskIndicator;
  todayStudyHours: number;
  performance: PerformanceStats;
}

export type NavigationView = 
  | 'dashboard' 
  | 'vision' 
  | 'tawjihi' 
  | 'bms-project' 
  | 'university' 
  | 'skills' 
  | 'habits'
  | 'health'
  | 'reading'
  | 'goals'
  | 'calendar'
  | 'journal'
  | 'ideas'
  | 'learning'
  | 'business' 
  | 'archive' 
  | 'media' 
  | 'notes' 
  | 'finance' 
  | 'ai-agent'
  | 'settings';

// ============================================
// NOTEFLOW TYPES - Knowledge Base
// ============================================

export interface NoteFolder {
  id: string;
  name: string;
  parentId: string | null;
  color?: string;
  icon?: string;
  order: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  folderId: string | null;
  tags: string[];
  isPinned: boolean;
  isFavorite: boolean;
  wordCount: number;
  courseId?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface AIConversation {
  id: string;
  noteId?: string;
  type: 'chat' | 'transcription' | 'vision' | 'edit';
  messages: AIMessage[];
  createdAt: Date;
}

export interface AIMessage {
  id: string;
  role: 'user' | 'assistant' | 'system';
  content: string;
  timestamp: Date;
}

export interface MeetingMinutes {
  id: string;
  noteId: string;
  topic: string;
  keyPoints: string[];
  actionItems: string[];
  decisions: string[];
  participants?: string[];
  duration?: number;
  createdAt: Date;
}

export interface VisionResult {
  id: string;
  noteId: string;
  type: 'image' | 'pdf';
  extractedText: string;
  structuredData?: Record<string, unknown>;
  insights?: string[];
  createdAt: Date;
}

export interface EditHistory {
  id: string;
  noteId: string;
  previousContent: string;
  newContent: string;
  action: string;
  createdAt: Date;
}

// ============================================
// WAR MODE TYPES
// ============================================

export interface WarModeSession {
  id: string;
  courseId: string;
  targetDuration: number;
  elapsed: number;
  startedAt: Date;
  status: 'active' | 'paused' | 'completed' | 'abandoned';
  xpRate: number;
}

export interface XPReward {
  action: string;
  xp: number;
  timestamp: Date;
}

// ============================================
// COMMANDER OS - Personal Command System
// ============================================

export interface MoodEntry {
  id: string;
  date: Date;
  mood: 'excellent' | 'good' | 'neutral' | 'bad' | 'terrible';
  emoji: string;
  notes?: string;
  createdAt: Date;
}

export interface FinancialTransaction {
  id: string;
  type: 'income' | 'expense';
  amount: number;
  category: string;
  description: string;
  date: Date;
  createdAt: Date;
}

export interface QuickNote {
  id: string;
  content: string;
  date: Date;
  createdAt: Date;
}

export interface StreakData {
  currentStreak: number;
  longestStreak: number;
  lastActiveDate: Date | null;
  totalDays: number;
}

export interface DailyLog {
  id: string;
  date: Date;
  tasksCompleted: number;
  studyMinutes: number;
  mood?: MoodEntry;
  notes?: QuickNote[];
  transactions?: FinancialTransaction[];
  createdAt: Date;
}

// ============================================
// LIFE OS - TAWJIHI TRACKER
// ============================================

export interface TawjihiSubject {
  id: string;
  name: string;
  type: 'academic' | 'vocational';
  category?: string; // نظري, عملي, رسم صناعي, مشروع
  maxGrade: number;
  grade?: number;
  weight: number; // الوزن في المعدل
  semester: 'first' | 'second';
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface TawjihiGoal {
  id: string;
  targetGrade: number; // الهدف من 500
  currentGrade: number;
  remainingPoints: number;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface StudyScheduleItem {
  id: string;
  subjectId: string;
  dayOfWeek: number;
  startTime: string;
  endTime: string;
  completed: boolean;
  notes?: string;
}

export interface ExamCountdown {
  id: string;
  name: string;
  date: Date;
  type: 'mock' | 'final' | 'subject';
  subjectId?: string;
}

// ============================================
// LIFE OS - BMS PROJECT MANAGER
// ============================================

export interface BMSComponent {
  id: string;
  name: string;
  category: 'microcontroller' | 'sensor' | 'actuator' | 'communication' | 'power' | 'other';
  status: 'needed' | 'ordered' | 'received' | 'integrated' | 'tested';
  quantity: number;
  notes?: string;
  price?: number;
  link?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface BMSTechnicalChallenge {
  id: string;
  title: string;
  description: string;
  status: 'open' | 'in_progress' | 'resolved' | 'blocked';
  priority: Priority;
  solution?: string;
  createdAt: Date;
  updatedAt: Date;
  resolvedAt?: Date;
}

export interface BMSProjectProgress {
  id: string;
  phase: string;
  progress: number; // 0-100
  status: 'not_started' | 'in_progress' | 'completed' | 'on_hold';
  startDate?: Date;
  endDate?: Date;
  notes?: string;
}

export interface BMSPresentationItem {
  id: string;
  title: string;
  description?: string;
  status: 'pending' | 'in_progress' | 'completed';
  order: number;
  notes?: string;
}

export interface CodeSnippet {
  id: string;
  title: string;
  code: string;
  language: string;
  category: 'arduino' | 'sensor' | 'communication' | 'display' | 'logic' | 'other';
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// LIFE OS - UNIVERSITY & SCHOLARSHIP
// ============================================

export interface UniversityInfo {
  id: string;
  name: string;
  country: string;
  city?: string;
  website?: string;
  ranking?: number;
  notes?: string;
}

export interface ScholarshipRequirement {
  id: string;
  title: string;
  description?: string;
  category: 'academic' | 'language' | 'documents' | 'financial' | 'other';
  status: 'pending' | 'in_progress' | 'completed' | 'not_applicable';
  deadline?: Date;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ApplicationDocument {
  id: string;
  name: string;
  type: string;
  status: 'needed' | 'preparing' | 'ready' | 'submitted';
  notes?: string;
  fileUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ApplicationTimeline {
  id: string;
  title: string;
  description?: string;
  date: Date;
  type: 'deadline' | 'milestone' | 'event' | 'reminder';
  status: 'upcoming' | 'completed' | 'missed';
  createdAt: Date;
}

export interface ChinaPreparation {
  id: string;
  category: 'visa' | 'housing' | 'language' | 'culture' | 'packing' | 'finance' | 'other';
  title: string;
  description?: string;
  status: 'pending' | 'in_progress' | 'completed';
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// LIFE OS - BUSINESS IDEAS
// ============================================

export interface BusinessIdea {
  id: string;
  title: string;
  description: string;
  category: 'security' | 'smart_home' | 'consulting' | 'education' | 'other';
  status: 'idea' | 'planning' | 'developing' | 'launched' | 'on_hold';
  priority: Priority;
  estimatedRevenue?: number;
  estimatedCost?: number;
  notes?: string;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectPortfolio {
  id: string;
  title: string;
  description: string;
  type: 'bms' | 'security' | 'smart_home' | 'iot' | 'other';
  status: 'planning' | 'in_progress' | 'completed';
  technologies: string[];
  images?: string[];
  githubUrl?: string;
  demoUrl?: string;
  startDate?: Date;
  endDate?: Date;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// LIFE OS - SKILLS TRACKER
// ============================================

export interface Skill {
  id: string;
  name: string;
  category: 'technical' | 'soft' | 'language' | 'other';
  level: 'beginner' | 'intermediate' | 'advanced' | 'expert';
  progress: number; // 0-100
  description?: string;
  resources: LearningResource[];
  practiceHours: number;
  lastPracticed?: Date;
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface LearningResource {
  id: string;
  skillId: string;
  title: string;
  type: 'course' | 'book' | 'video' | 'documentation' | 'project' | 'other';
  url?: string;
  status: 'not_started' | 'in_progress' | 'completed';
  progress: number; // 0-100
  notes?: string;
  createdAt: Date;
}

// ============================================
// LIFE OS - LIFE GOALS
// ============================================

export interface VisionBoardItem {
  id: string;
  title: string;
  description?: string;
  category: 'education' | 'career' | 'personal' | 'financial' | 'travel' | 'other';
  imageUrl?: string;
  status: 'dreaming' | 'planning' | 'working' | 'achieved';
  targetDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface YearlyGoal {
  id: string;
  year: number;
  title: string;
  description?: string;
  category: 'education' | 'career' | 'personal' | 'financial' | 'other';
  progress: number;
  milestones: QuarterlyMilestone[];
  status: 'not_started' | 'in_progress' | 'completed' | 'on_hold';
  createdAt: Date;
  updatedAt: Date;
}

export interface QuarterlyMilestone {
  id: string;
  goalId: string;
  quarter: 1 | 2 | 3 | 4;
  title: string;
  description?: string;
  status: 'pending' | 'in_progress' | 'completed';
  tasks: WeeklyTask[];
  createdAt: Date;
}

export interface WeeklyTask {
  id: string;
  milestoneId: string;
  title: string;
  description?: string;
  weekNumber: number;
  status: 'pending' | 'in_progress' | 'completed';
  priority: Priority;
  dueDate?: Date;
  completedAt?: Date;
  createdAt: Date;
}

// ============================================
// USER PROFILE
// ============================================

export interface UserProfile {
  name: string;
  age: number;
  location: string;
  education: string;
  major: string;
  personality: string;
  goals: string[];
  avatar?: string;
}

// ============================================
// AI AGENT MESSAGE
// ============================================

export interface AIAgentMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: Date;
  action?: {
    type: string;
    data?: unknown;
  };
}

// ============================================
// MEDIA & STORAGE - نظام التخزين الشامل
// ============================================

export interface MediaFile {
  id: string;
  name: string;
  type: 'image' | 'video' | 'document' | 'audio' | 'link';
  category: 'project' | 'education' | 'personal' | 'bms' | 'scholarship' | 'other';
  url: string;
  thumbnail?: string;
  description?: string;
  tags: string[];
  folderId?: string;
  relatedProject?: string;
  size?: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface MediaFolder {
  id: string;
  name: string;
  parentId?: string;
  color?: string;
  icon?: string;
  order: number;
  createdAt: Date;
}

export interface ArchiveTopic {
  id: string;
  title: string;
  content: string;
  category: 'arduino' | 'bms' | 'programming' | 'electronics' | 'education' | 'scholarship' | 'other';
  tags: string[];
  importance: 'critical' | 'important' | 'normal';
  mediaIds: string[];
  sourceUrl?: string;
  isFavorite: boolean;
  lastReviewed?: Date;
  reviewCount: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectArchive {
  id: string;
  name: string;
  description: string;
  type: 'bms' | 'security' | 'smart_home' | 'iot' | 'website' | 'other';
  status: 'planning' | 'active' | 'completed' | 'on_hold';
  startDate?: Date;
  endDate?: Date;
  documents: string[]; // MediaFile IDs
  codeSnippetIds: string[];
  notes: string;
  progress: number;
  createdAt: Date;
  updatedAt: Date;
}

export interface AIConversationSession {
  id: string;
  title: string;
  messages: AIAgentMessage[];
  context: 'general' | 'study' | 'bms' | 'scholarship' | 'coding' | 'career';
  summary?: string;
  isPinned: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// USER EXPERIENCE & AUTO-TRACKING
// ============================================

export interface UserExperience {
  id: string;
  type: 'skill' | 'achievement' | 'project' | 'learning' | 'event' | 'other';
  title: string;
  description: string;
  category: string;
  date: Date;
  source: 'user_input' | 'ai_extracted' | 'ai_question';
  relatedConversationId?: string;
  tags: string[];
  importance: 'high' | 'medium' | 'low';
  createdAt: Date;
  updatedAt: Date;
}

export interface DailyRecord {
  id: string;
  date: Date;
  type: 'study_hours' | 'skill_practice' | 'achievement' | 'progress' | 'expense' | 'income' | 'note' | 'custom';
  category: string;
  title: string;
  value: number;
  unit: string;
  description?: string;
  source: 'manual' | 'ai_recorded' | 'ai_question';
  relatedConversationId?: string;
  createdAt: Date;
}

// ============================================
// ⚔️ EXECUTION ENGINE - محرك التنفيذ
// ============================================

export interface ExecutionTask {
  id: string;
  title: string;
  description: string;
  type: 'study' | 'project' | 'scholarship' | 'skill' | 'finance' | 'urgent';
  priority: 'critical' | 'high' | 'medium' | 'low';
  source: 'auto_generated' | 'ai_suggested' | 'user_created';
  relatedData?: {
    subjectId?: string;
    componentId?: string;
    requirementId?: string;
    skillId?: string;
  };
  xpReward: number;
  completed: boolean;
  completedAt?: Date;
  date: Date;
  createdAt: Date;
}

export interface SmartAlert {
  id: string;
  type: 'warning' | 'critical' | 'info' | 'success';
  category: 'grade' | 'deadline' | 'finance' | 'project' | 'streak' | 'general';
  title: string;
  message: string;
  action?: {
    label: string;
    view: NavigationView;
  };
  dismissed: boolean;
  timestamp: Date;
}

export interface HardModeSettings {
  enabled: boolean;
  activatedAt?: Date;
  xpMultiplier: number;
  restrictions: {
    noEasyTasks: boolean;
    noPostponement: boolean;
    onlyDifficult: boolean;
  };
  stats: {
    tasksCompleted: number;
    xpEarned: number;
    daysActive: number;
  };
}

export interface ExecutionEngineState {
  dailyMissions: ExecutionTask[];
  alerts: SmartAlert[];
  hardMode: HardModeSettings;
  lastMissionGeneration: Date | null;
  commandsQueue: AICommand[];
}

export interface AICommand {
  id: string;
  type: 'add_exam' | 'add_task' | 'set_priority' | 'create_study_session' | 'record_progress' | 'update_grade';
  data: Record<string, unknown>;
  executed: boolean;
  result?: string;
  timestamp: Date;
}

// ============================================
// 🏥 HEALTH & FITNESS - الصحة واللياقة
// ============================================

export interface HealthRecord {
  id: string;
  date: Date;
  weight?: number;
  height?: number;
  waterGlasses: number;
  sleepHours: number;
  sleepQuality: 'excellent' | 'good' | 'fair' | 'poor';
  steps: number;
  exerciseMinutes: number;
  mood: 'great' | 'good' | 'okay' | 'bad' | 'terrible';
  energy: number; // 1-10
  notes?: string;
  createdAt: Date;
}

export interface WorkoutSession {
  id: string;
  type: 'cardio' | 'strength' | 'flexibility' | 'sports' | 'walking' | 'other';
  name: string;
  duration: number; // minutes
  calories?: number;
  intensity: 'low' | 'medium' | 'high';
  exercises: WorkoutExercise[];
  date: Date;
  completed: boolean;
  notes?: string;
  createdAt: Date;
}

export interface WorkoutExercise {
  id: string;
  name: string;
  sets?: number;
  reps?: number;
  weight?: number;
  duration?: number;
  completed: boolean;
}

export interface NutritionEntry {
  id: string;
  date: Date;
  mealType: 'breakfast' | 'lunch' | 'dinner' | 'snack';
  foods: FoodItem[];
  totalCalories: number;
  totalProtein: number;
  totalCarbs: number;
  totalFat: number;
  waterGlasses: number;
  notes?: string;
  createdAt: Date;
}

export interface FoodItem {
  id: string;
  name: string;
  amount: number;
  unit: string;
  calories: number;
  protein: number;
  carbs: number;
  fat: number;
}

export interface HealthGoal {
  id: string;
  type: 'weight' | 'steps' | 'water' | 'sleep' | 'exercise' | 'calories';
  target: number;
  current: number;
  unit: string;
  deadline?: Date;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// 📚 READING & BOOKS - القراءة والكتب
// ============================================

export interface Book {
  id: string;
  title: string;
  author: string;
  category: 'self-development' | 'technical' | 'fiction' | 'religious' | 'educational' | 'other';
  status: 'to-read' | 'reading' | 'completed' | 'on-hold';
  totalPages: number;
  currentPage: number;
  startDate?: Date;
  endDate?: Date;
  rating?: number;
  notes?: string;
  favoriteQuotes: string[];
  isbn?: string;
  coverUrl?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ReadingSession {
  id: string;
  bookId: string;
  pagesRead: number;
  duration: number; // minutes
  date: Date;
  notes?: string;
  createdAt: Date;
}

export interface ReadingGoal {
  id: string;
  year: number;
  targetBooks: number;
  currentBooks: number;
  targetPages: number;
  currentPages: number;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// 🔄 HABITS - العادات اليومية
// ============================================

export interface Habit {
  id: string;
  name: string;
  description?: string;
  category: 'health' | 'productivity' | 'learning' | 'spiritual' | 'social' | 'personal' | 'other';
  frequency: 'daily' | 'weekly' | 'monthly';
  targetDays?: number[]; // 0-6 for weekly
  color: string;
  icon: string;
  reminder?: string;
  isActive: boolean;
  streak: number;
  longestStreak: number;
  completedDates: Date[];
  createdAt: Date;
  updatedAt: Date;
}

export interface HabitCompletion {
  id: string;
  habitId: string;
  date: Date;
  completed: boolean;
  notes?: string;
  createdAt: Date;
}

// ============================================
// 🎯 GOALS - الأهداف المتقدمة
// ============================================

export interface Goal {
  id: string;
  title: string;
  description?: string;
  category: 'career' | 'education' | 'health' | 'finance' | 'personal' | 'relationships' | 'spiritual' | 'other';
  type: 'short-term' | 'medium-term' | 'long-term' | 'lifetime';
  priority: 'critical' | 'high' | 'medium' | 'low';
  status: 'not-started' | 'in-progress' | 'on-hold' | 'completed' | 'cancelled';
  progress: number; // 0-100
  milestones: Milestone[];
  subGoals: string[]; // Goal IDs
  parentGoalId?: string;
  startDate?: Date;
  targetDate?: Date;
  completedDate?: Date;
  xpReward: number;
  tags: string[];
  createdAt: Date;
  updatedAt: Date;
}

export interface Milestone {
  id: string;
  title: string;
  description?: string;
  status: 'pending' | 'in-progress' | 'completed';
  dueDate?: Date;
  completedDate?: Date;
  order: number;
}

// ============================================
// 📅 CALENDAR & EVENTS - التقويم والأحداث
// ============================================

export interface CalendarEvent {
  id: string;
  title: string;
  description?: string;
  type: 'meeting' | 'task' | 'reminder' | 'deadline' | 'event' | 'study' | 'other';
  startDate: Date;
  endDate?: Date;
  allDay: boolean;
  location?: string;
  color: string;
  reminders: EventReminder[];
  recurring?: RecurringPattern;
  linkedGoalId?: string;
  linkedProjectId?: string;
  completed: boolean;
  createdAt: Date;
  updatedAt: Date;
}

export interface EventReminder {
  id: string;
  time: number; // minutes before event
  type: 'notification' | 'email';
  sent: boolean;
}

export interface RecurringPattern {
  frequency: 'daily' | 'weekly' | 'monthly' | 'yearly';
  interval: number;
  endDate?: Date;
  count?: number;
}

// ============================================
// 🎨 CREATIVE PROJECTS - المشاريع الإبداعية
// ============================================

export interface CreativeProject {
  id: string;
  title: string;
  description: string;
  type: 'writing' | 'art' | 'music' | 'video' | 'photography' | 'design' | 'code' | 'other';
  status: 'idea' | 'planning' | 'in-progress' | 'review' | 'completed' | 'published';
  progress: number;
  coverImage?: string;
  tags: string[];
  collaborators: string[];
  assets: ProjectAsset[];
  tasks: CreativeTask[];
  startDate?: Date;
  targetDate?: Date;
  completedDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface ProjectAsset {
  id: string;
  name: string;
  type: 'image' | 'video' | 'audio' | 'document' | 'link' | 'other';
  url: string;
  size?: number;
  createdAt: Date;
}

export interface CreativeTask {
  id: string;
  title: string;
  description?: string;
  status: 'todo' | 'in-progress' | 'completed';
  priority: 'high' | 'medium' | 'low';
  dueDate?: Date;
  completedDate?: Date;
  order: number;
}

// ============================================
// 💡 IDEAS & BRAINSTORMING - الأفكار والعصف الذهني
// ============================================

export interface Idea {
  id: string;
  title: string;
  description: string;
  category: 'business' | 'creative' | 'technical' | 'personal' | 'social' | 'other';
  status: 'new' | 'exploring' | 'developing' | 'implemented' | 'archived';
  priority: 'high' | 'medium' | 'low';
  tags: string[];
  linkedProjectIds: string[];
  source: string;
  references: string[];
  votes: number; // for prioritization
  createdAt: Date;
  updatedAt: Date;
}

export interface BrainstormSession {
  id: string;
  title: string;
  topic: string;
  ideas: string[];
  conclusions: string[];
  actionItems: string[];
  date: Date;
  duration: number;
  createdAt: Date;
}

// ============================================
// 📊 ANALYTICS & INSIGHTS - التحليلات والرؤى
// ============================================

export interface DailyAnalytics {
  id: string;
  date: Date;
  productivity: number; // 0-100
  focus: number; // 0-100
  energy: number; // 0-100
  mood: number; // 0-100
  tasksCompleted: number;
  tasksTotal: number;
  studyMinutes: number;
  exerciseMinutes: number;
  sleepHours: number;
  waterGlasses: number;
  readingMinutes: number;
  socialInteractions: number;
  screenTime?: number;
  createdAt: Date;
}

export interface WeeklyReport {
  id: string;
  weekStart: Date;
  weekEnd: Date;
  summary: string;
  highlights: string[];
  improvements: string[];
  goalsProgress: { goalId: string; progress: number }[];
  topSkills: string[];
  streaksMaintained: number;
  xpEarned: number;
  createdAt: Date;
}

// ============================================
// 🔗 INTEGRATIONS - التكاملات
// ============================================

export interface Integration {
  id: string;
  name: string;
  type: 'calendar' | 'notes' | 'fitness' | 'music' | 'social' | 'other';
  connected: boolean;
  lastSync?: Date;
  settings: Record<string, unknown>;
  createdAt: Date;
}

// ============================================
// 🎓 LEARNING PATH - مسارات التعلم
// ============================================

export interface LearningPath {
  id: string;
  title: string;
  description: string;
  category: string;
  difficulty: 'beginner' | 'intermediate' | 'advanced';
  totalHours: number;
  completedHours: number;
  resources: LearningPathResource[];
  skills: string[];
  certificate?: string;
  status: 'not-started' | 'in-progress' | 'completed';
  startDate?: Date;
  targetDate?: Date;
  createdAt: Date;
  updatedAt: Date;
}

export interface LearningPathResource {
  id: string;
  title: string;
  type: 'video' | 'article' | 'book' | 'course' | 'project' | 'quiz';
  url?: string;
  duration?: number;
  completed: boolean;
  order: number;
}

// ============================================
// 💬 JOURNAL - اليوميات والتأملات
// ============================================

export interface JournalEntry {
  id: string;
  date: Date;
  title?: string;
  content: string;
  mood: 'great' | 'good' | 'okay' | 'bad' | 'terrible';
  gratitude: string[];
  achievements: string[];
  challenges: string[];
  tomorrowGoals: string[];
  tags: string[];
  isPrivate: boolean;
  createdAt: Date;
  updatedAt: Date;
}

// ============================================
// 🏆 ACHIEVEMENTS SYSTEM - نظام الإنجازات
// ============================================

export interface Achievement {
  id: string;
  title: string;
  description: string;
  category: 'productivity' | 'health' | 'learning' | 'social' | 'creative' | 'special';
  icon: string;
  rarity: 'common' | 'uncommon' | 'rare' | 'epic' | 'legendary';
  xpReward: number;
  requirement: {
    type: 'streak' | 'count' | 'time' | 'special';
    target: number;
    current: number;
  };
  unlocked: boolean;
  unlockedAt?: Date;
  createdAt: Date;
}

// ============================================
// 📱 WIDGETS - الأدوات المصغرة
// ============================================

export interface WidgetConfig {
  id: string;
  type: 'quote' | 'clock' | 'weather' | 'tasks' | 'habit' | 'goal' | 'stats';
  position: { x: number; y: number };
  size: 'small' | 'medium' | 'large';
  settings: Record<string, unknown>;
  isVisible: boolean;
  createdAt: Date;
}

// ============================================
// 📝 REVIEW - المراجعات والتأملات
// ============================================

export interface DailyReview {
  id: string;
  date: Date;
  type: 'daily' | 'weekly' | 'monthly';
  productivity: number; // 1-10
  mood: number; // 1-10
  energy: number; // 1-10
  wins: string[]; // الإنجازات
  challenges: string[]; // التحديات
  lessons: string[]; // الدروس المستفادة
  gratitude: string[]; // الامتنان
  tomorrowGoals: string[]; // أهداف الغد
  reflectionQuestions: ReflectionAnswer[];
  notes?: string;
  createdAt: Date;
  updatedAt: Date;
}

export interface ReflectionAnswer {
  questionId: string;
  question: string;
  answer: string;
}

export interface ReflectionQuestion {
  id: string;
  question: string;
  category: 'daily' | 'weekly' | 'monthly';
  order: number;
  isActive: boolean;
}

// ============================================
// 🔗 RESOURCE LINK - روابط التعلم
// ============================================

export interface ResourceLink {
  id: string;
  title: string;
  url: string;
  category: 'article' | 'video' | 'course' | 'documentation' | 'tool' | 'other';
  tags: string[];
  status: 'to-read' | 'reading' | 'completed' | 'archived';
  notes?: string;
  rating?: number;
  createdAt: Date;
  updatedAt: Date;
}
